added the make package target.  Builds a faxien style package.

diff --git a/tools/utilities/application_generator b/tools/utilities/application_generator
--- a/tools/utilities/application_generator
+++ b/tools/utilities/application_generator
@@ -21,19 +21,22 @@ APP_NAME=$1
 APP_NAME_UPPER_CASE=$(echo $APP_NAME | tr a-z A-Z)
 PREFIX=$2
 
+if [ -e ../../lib/$APP_NAME ];then
+	echo "an application with name $APP_NAME already exists would you like to delete it [y|N] $> \c"
+	read DEL
+	if [ "$DEL" != "y" ];then
+		echo "aborting application creation"
+		exit 1
+	fi
+	echo "deleting $APP_NAME"
+	rm -rf ../../lib/$APP_NAME
+fi
+
+
 cd ../.appgen
 echo `pwd`
 
 cp -r blank_app $APP_NAME
-cp -r blank_app_rel "$APP_NAME"_rel
-
-cd "$APP_NAME"_rel
-ls blank_app* | ../rename.sh blank_app $APP_NAME
-cd ..
-
-# The base directory of the release
-./substitute.sh %%APP_NAME%% $APP_NAME "$APP_NAME"_rel/"$APP_NAME"_rel.rel.src
-
 
 cd $APP_NAME/src
 ls ba* | ../../rename.sh ba $PREFIX
@@ -49,23 +52,13 @@ cd -
 ./substitute.sh %%APP_NAME_UPPER_CASE%% $APP_NAME_UPPER_CASE $APP_NAME/src/Makefile
 ./substitute.sh %%PFX%% $PREFIX $APP_NAME/src/Makefile
 
-./substitute.sh %%APP_NAME%% $APP_NAME $APP_NAME/src/"$APP_NAME".erl
-./substitute.sh %%PFX%% $PREFIX $APP_NAME/src/"$APP_NAME".erl
-./substitute.sh %%PFX%% $PREFIX $APP_NAME/src/"$PREFIX"_sup.erl
-./substitute.sh %%APP_NAME%% $APP_NAME $APP_NAME/src/"$PREFIX"_sup.erl
-./substitute.sh %%PFX%% $PREFIX $APP_NAME/src/"$PREFIX"_server.erl
-./substitute.sh %%APP_NAME%% $APP_NAME $APP_NAME/src/"$PREFIX"_server.erl
-
 # include directory
 mv $APP_NAME/include/blank_app.hrl $APP_NAME/include/"$APP_NAME".hrl
 
-find $APP_NAME -name ".svn" | xargs rm -r
 mv $APP_NAME ../../lib
-mv "$APP_NAME"_rel ../../release
 
 echo ""
 echo "$APP_NAME has been generated and placed under lib/$APP_NAME"
-echo $APP_NAME"_rel has been generated and placed under release/$APP_NAME""_rel"
 echo ""
 
 cd ../utilities
